/**
 * Generates embedded-streamer.ts with webrtc-streamer.exe as base64
 * Run this before building to embed the binary
 */

import * as fs from "fs";
import * as path from "path";

const ROOT = path.join(import.meta.dir, "..");
const STREAMER_EXE = path.join(ROOT, "bin", "webrtc-streamer.exe");
const OUTPUT_FILE = path.join(ROOT, "src", "embedded-streamer.ts");

if (!fs.existsSync(STREAMER_EXE)) {
  console.error("[embed] ERROR: bin/webrtc-streamer.exe not found");
  process.exit(1);
}

console.log("[embed] Reading webrtc-streamer.exe...");
const buffer = fs.readFileSync(STREAMER_EXE);
const base64 = buffer.toString("base64");
const sizeMB = (buffer.length / 1024 / 1024).toFixed(2);

console.log(`[embed] Size: ${sizeMB} MB (${base64.length} chars base64)`);

// Generate TypeScript file with embedded binary
const output = `/**
 * AUTO-GENERATED - DO NOT EDIT
 * Contains webrtc-streamer.exe as embedded base64
 * Generated by: bun scripts/embed-streamer.ts
 */

export const STREAMER_SIZE = ${buffer.length};
export const STREAMER_BASE64 = "${base64}";
`;

console.log("[embed] Writing src/embedded-streamer.ts...");
fs.writeFileSync(OUTPUT_FILE, output);

console.log("[embed] Done! Run 'bun run build' to compile single exe");
